#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RIGHT_HOPPER_DOWN 143
#define LEFT_HOPPER_DOWN  108
#define ROTATION          100

#define ELEV_ENCODER_UP_VAL -24000

#include "2014RobotTeleop.c"
