#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RIGHT_HOPPER_DOWN 148
#define LEFT_HOPPER_DOWN  96
#define ROTATION          100

#define ELEV_ENCODER_UP_VAL -18000

#include "2014RobotTeleop.c"
