#pragma config(StandardModel, "tommy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RIGHT_HOPPER_DOWN 129
#define LEFT_HOPPER_DOWN  110
#define ROTATION          90

#define ELEV_ENCODER_UP_VAL -17000

#include "2014RobotTeleop.c"
