#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"

task main()
{
  int dir;
	int strength1, strength2, strength3, strength4, strength5;

	// the default DSP mode is 1200 Hz.
  tHTIRS2DSPMode mode = DSP_1200;

  while(true)
  {
    // You can switch between the two different DSP modes by pressing the
    // orange enter button

    while (true)
    {
      // set the DSP to the new mode
      if (HTIRS2setDSPMode(IRSeeker, mode))
        break; // Sensor initialized

      PlaySound(soundShortBlip);
      nxtDisplayCenteredTextLine(6, "Connect Sensor");
      nxtDisplayCenteredTextLine(7, "to Port S2");
      wait1Msec(100);
    }

    eraseDisplay();

    while (true)
    {

      // read the current modulated signal direction
      dir = HTIRS2readACDir(IRSeeker);
      if (dir < 0)
        break; // I2C read error occurred

      if (!HTIRS2readAllACStrength(IRSeeker, strength1, strength2, strength3, strength4, strength5 ))
        break; // I2C read error occurred

      string tmpStr;

      StringFormat(tmpStr, "Direction: %d", dir);
      nxtDisplayTextLine(3, tmpStr);
      StringFormat(tmpStr, "Strength: %d", strength3);
      nxtDisplayTextLine(4, tmpStr);

      if (dir < 5) {
      	  // turn right
          motor[motorD] = 30;
          motor[motorE] = -30;
      } else if (dir > 5) {
    	  // turn left
          motor[motorD] = -30;
          motor[motorE] = 30;
      } else if (strength3 < 110) {
          motor[motorD] = 30;
          motor[motorE] = 30;
      } else {
          motor[motorD] = 0;
          motor[motorE] = 0;
     }
    }
  }



}
