#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     lightSensor,    sensorLightInactive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveRight,    tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     driveLeft,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     grabberArm,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     driveSide,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    gravityShelf,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    IRServo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    Ramp,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../library/sensors/drivers/hitechnic-sensormux.h"
#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../library/sensors/drivers/hitechnic-compass.h"
#include "../library/sensors/drivers/lego-light.h"
#include "../library/sensors/drivers/lego-touch.h"

#include "../Competition Code/Lib/Lib12-13.c"


task main()
{
  	int dir;
	int strength1, strength2, strength3, strength4, strength5;

	// the default DSP mode is 1200 Hz.
  	tHTIRS2DSPMode mode = DSP_1200;

    // You can switch between the two different DSP modes by pressing the
    // orange enter button

    eraseDisplay();

    while (true)
    {
      	// read the current modulated signal direction
      	dir = HTIRS2readACDir(IRSeeker);
      	if (dir < 0)
        	break; // I2C read error occurred

      	if (!HTIRS2readAllACStrength(IRSeeker, strength1, strength2, strength3, strength4, strength5 ))
        	break; // I2C read error occurred

      	string tmpStr;

		StringFormat(tmpStr, "Direction: %d", dir);
		nxtDisplayTextLine(3, tmpStr);
		StringFormat(tmpStr, "Strength 2: %d", strength2);
		nxtDisplayTextLine(4, tmpStr);
		StringFormat(tmpStr, "Strength 3: %d", strength3);
		nxtDisplayTextLine(5, tmpStr);
		StringFormat(tmpStr, "Strength 4: %d", strength4);
		nxtDisplayTextLine(6, tmpStr);

    }
}
