#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearRight, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearLeft, tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivetrain_defs.h"
#include "drivetrain_square.h"
#include "dead_reckon.h"

task main()
{
    initializeMotors();

    init_path();
    add_segment(0, 90, 20);
    stop_path();
    dead_reckon();
}
