#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ,               sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     ,               sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveRight,    tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     driveLeft,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     grabberArm,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     driveSide,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    gravityShelf,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    IRServo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    ringGrab,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Lib/Lib12-13.c"
#include "firmwareVersion.h"
#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"

////////////////////////////////////////////////////////////////////////////////////////////////////
#define SHELFUP 0
#define SHELFDOWN 228
#define IRUP 121
#define IRDOWN 0
#define IRRING 148
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  servo[IRServo]= IRUP;

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	 initializeRobot();

	  waitForStart(); // Wait for the beginning of autonomous phase.

	  while (true)//infinite loop. Put all code in here to keep it running for the whole match
	  {
	    //getJoystickSettings(joystick);//Get joystick input

	  	//forwarddrivetrain();//call the forwarddrivetrain function
	  	//sidewaysdrivetrain();//call the sidewaysdrivetrain function

	  	//Variable that keeps track of the last IR Seeker value.
	    int lastValue = 0;

	    int dir;
		int strength1, strength2, strength3, strength4, strength5;

		// the default DSP mode is 1200 Hz.
	    tHTIRS2DSPMode mode = DSP_1200;

	    // set the DSP to the new mode
        if (HTIRS2setDSPMode(IRSeeker, mode))

	    while(1==1)
	    {
			// read the current modulated signal direction
		    dir = HTIRS2readACDir(IRSeeker);
		    if (dir < 0)
		    break; // I2C read error occurred

		    if (!HTIRS2readAllACStrength(IRSeeker, strength1, strength2, strength3, strength4, strength5 ))
		    break; // I2C read error occurred

	        nxtDisplayCenteredBigTextLine(3, "%d", lastValue);
	        lastValue = SensorValue[IRSeeker];

	        if (lastValue == 0)
	        {
	        	nMotorPIDSpeedCtrl[driveRight] = mtrSpeedReg;
	        	nMotorPIDSpeedCtrl[driveLeft] = mtrSpeedReg;
	            motor[driveRight] = -75;
	            motor[driveLeft] = 75;
	            wait1Msec(1000);
	         }
	         else if (lastValue > 5)   //If the right side of the sensor detects the beacon...
	         {
	             //turn right.
	         	nMotorPIDSpeedCtrl[driveRight] = mtrSpeedReg;
	        	nMotorPIDSpeedCtrl[driveLeft] = mtrSpeedReg;
	           	 motor[driveRight] = -75;
	             motor[driveLeft] = 75;
	         }
	         else if(lastValue < 5)      //If the left side of the sensor detects the beacon (or doesn't see it)...
	         {
	             //turn left.
	             nMotorPIDSpeedCtrl[driveRight] = mtrSpeedReg;
	        	 nMotorPIDSpeedCtrl[driveLeft] = mtrSpeedReg;
	             motor[driveRight] = 75;
	             motor[driveLeft] = -75;
	          }
	          else if(lastValue == 5)     //If the sensor is lined up with the beacon...
	          {
	             //drive straight.
	             nMotorPIDSpeedCtrl[driveRight] = mtrSpeedReg;
	        	 nMotorPIDSpeedCtrl[driveLeft] = mtrSpeedReg;
	             motor[driveRight] = -85;
	             motor[driveLeft] = -85;
	          }
	          else if (strength3 < 110)
	          {
		          motor[motorD] = 30;
		          motor[motorE] = 30;
		      }
		      else
		      {
		          motor[motorD] = 0;
		          motor[motorE] = 0;
		          servo[gravityShelf] = SHELFUP;
		          servo[IRServo] = IRRING;
		          servo[gravityShelf] = SHELFDOWN;
		      }
	      }
}


  while (true)
  {}
}
