#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define ENCPERINCH 108
#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"
#include "..\library\sensors\drivers\hitechnic-compass.h"
#include "..\library\DrivetrainSquare.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void lookForBeacon()
{
  	int dir;
    bool done;
	int strength1, strength2, strength3, strength4, strength5;

	// the default DSP mode is 1200 Hz.
  	tHTIRS2DSPMode mode = DSP_1200;

    // You can switch between the two different DSP modes by pressing the
    // orange enter button
    moveForwardOn(70);
    eraseDisplay();
    done = false;

    while (!done)
    {
      	// read the current modulated signal direction
      	dir = HTIRS2readACDir(IRSeeker);
        nxtDisplayCenteredTextLine(3, "Dir %d", dir);

      	if (dir < 0)
        	break; // I2C read error occurred

      	if (!HTIRS2readAllACStrength(IRSeeker, strength1, strength2, strength3, strength4, strength5 ))
        	break; // I2C read error occurred


        if (dir <= 5) {
            done = true;
        }
    }
    moveForwardOff();
}

void moveAcrossField()
{
    moveForward(50,100);
    turn(45,20);
    moveForward(30, 100);
    turn(45,20);
}

task main()
{
    waitForStart();

 	moveAcrossField();
    lookForBeacon();

    while (true) { }
}
