#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define ENCPERINCH 108
#include "..\library\DrivetrainSquare.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    waitForStart();

 	moveForward(65,100);

    while (true) { }
}
