#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define ENCPERINCH 108

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "..\library\sensors\drivers\hitechnic-compass.h"
#include "..\library\DrivetrainSquare.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#define RIGHT_HOPPER_DOWN 148
#define LEFT_HOPPER_DOWN  96
#define ROTATION          100
#define LEFT_HOPPER_UP LEFT_HOPPER_DOWN + ROTATION
#define RIGHT_HOPPER_UP RIGHT_HOPPER_DOWN - ROTATION
#define ELEV_ENCODER_UP_VAL -18000

void initializeRobot()
{
	servo[leftHopper] = LEFT_HOPPER_DOWN;
    servo[rightHopper] = RIGHT_HOPPER_DOWN;
}

void moveWaterWheel()
{
    motor[waterWheel] = 20;
    wait1Msec(3000);
    motor[waterWheel] = 0;
}

void raiseElevator()
{
	int val;

	nMotorEncoder[rightElevator] = 0;

	motor[leftElevator] = 70;
	motor[rightElevator] = -70;

    val = nMotorEncoder[rightElevator];
    while (val > ELEV_ENCODER_UP_VAL) {
        val = nMotorEncoder[rightElevator];
    }
	motor[leftElevator] = 0;
	motor[rightElevator] = 0;
}

void raiseHopper()
{
    servo[leftHopper] = LEFT_HOPPER_UP;
    servo[rightHopper] = RIGHT_HOPPER_UP;
}

void dumpBlocks()
{
	moveWaterWheel();
}

task main()
{
    initializeRobot();

  //waitForStart(); // Wait for the beginning of autonomous phase.

	raiseElevator();

	raiseHopper();

	moveBackward(12, 75);

	dumpBlocks();

	// movetoRamp();

    while (true)
    {}
}
