#pragma config(StandardModel, "tommy")

#define ENCPERINCH 108
#include "..\library\DrivetrainSquare.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 	moveForward(65,100);
}
