#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define ENCPERINCH 108
#define BLOCK_SERVO_RETRACTED 6
#define BLOCK_SERVO_EXTENDED  250

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../library/sensors/drivers/hitechnic-compass.h"
#include "../library/sensors/drivers/hitechnic-protoboard.h"
#include "../library/DrivetrainSquare.c"
#include "../library/dead_reckon.h"
#include "../library/limitSwitch.h"
#include "../library/light_strip.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#define RIGHT_HOPPER_DOWN 143
#define LEFT_HOPPER_DOWN  108
#define ROTATION          100
#define LEFT_HOPPER_UP LEFT_HOPPER_DOWN + ROTATION
#define RIGHT_HOPPER_UP RIGHT_HOPPER_DOWN - ROTATION
#define ELEV_ENCODER_UP_VAL -18000

#define SERVO_FORWARD 0
#define SERVO_REVERSE 256
#define SERVO_STOPPED 127

int travelDistance[] = {16, 9, 24, 9};
int compensation[] = {0, -2, -6, -8};

/*
 * RobotC bug.  The following does not initialize correctly
 */
segment_t dead_reckon_from_b3[3] = {
    { 0, 12, 100 },
    { 90, 18, 100 },
    { 90, 24, 100 },
};

segment_t dead_reckon_from_b2[3] = {
    { 0, 23, 100 },
    { 90, 18, 100 },
    { 90, 24, 100 },
};

segment_t dead_reckon_from_b1[3] = {
    { 0, 45, 100 },
    { 90, 18, 100 },
    { 90, 24, 100 },
};

segment_t dead_reckon_from_b0[3] = {
    { 0, 55, 100 },
    { 90, 18, 100 },
    { 90, 24, 100 },
};

/*
 * Work around the RobotC bug
 */
void initSegment(segment_t *seg, int idx, int turn, int inches, int speed)
{
    seg[idx].turn = turn;
    seg[idx].inches = inches;
    seg[idx].speed = speed;
}

void initializeRobot()
{
    tHTIRS2DSPMode mode = DSP_1200;
    HTIRS2setDSPMode(IRSeeker, mode);

    servoChangeRate[blockDump] = 5;

	servo[blockDump] = BLOCK_SERVO_RETRACTED;

    servo[middleElev] = SERVO_STOPPED;

    lightStripInit(0x1F);
    displayRestingPulse();

	/*
	 * Work around the RobotC bug
	 */
    initSegment(dead_reckon_from_b3, 0, 0, -12, 100);
    initSegment(dead_reckon_from_b3, 1, -90, -24, 100);
    initSegment(dead_reckon_from_b3, 2, -90, 32, 100);
    initSegment(dead_reckon_from_b3, 2, 0, 0, 0);

    initSegment(dead_reckon_from_b2, 0, 0, -23, 100);
    initSegment(dead_reckon_from_b2, 1, -90, -24, 100);
    initSegment(dead_reckon_from_b2, 2, -90, -32, 100);
    initSegment(dead_reckon_from_b2, 2, 0, 0, 0);

    initSegment(dead_reckon_from_b1, 0, 0, -45, 100);
    initSegment(dead_reckon_from_b1, 1, -90, -24, 100);
    initSegment(dead_reckon_from_b1, 2, -90, -32, 100);
    initSegment(dead_reckon_from_b1, 2, 0, 0, 0);

    initSegment(dead_reckon_from_b0, 0, 0, -55, 100);
    initSegment(dead_reckon_from_b0, 1, -90, -24, 100);
    initSegment(dead_reckon_from_b0, 2, -90, -32, 100);
    initSegment(dead_reckon_from_b0, 2, 0, 0, 0);
}

void raiseElevator()
{
	int val;

	nMotorEncoder[rightElevator] = 0;

	motor[leftElevator] = 70;
	motor[rightElevator] = -70;

    val = nMotorEncoder[rightElevator];
    while (val > ELEV_ENCODER_UP_VAL) {
        val = nMotorEncoder[rightElevator];
    }
	motor[leftElevator] = 0;
	motor[rightElevator] = 0;
}

void moveToRamp(int basket)
{
    switch (basket) {
    case 0:
        deadReckon(dead_reckon_from_b0);
        break;
    case 1:
        deadReckon(dead_reckon_from_b1);
        break;
    case 2:
        deadReckon(dead_reckon_from_b2);
       break;
    case 3:
        deadReckon(dead_reckon_from_b3);
        break;
    }
}

void dumpBlock()
{
    servoChangeRate[blockDump] = 10;
    servo[blockDump] = BLOCK_SERVO_EXTENDED;
    wait1Msec(1500);

    servoChangeRate[blockDump] = 10;

    for (int i = 0; i < 5; i++) {
        servo[blockDump] = BLOCK_SERVO_EXTENDED - 20;
        wait1Msec(100);
        servo[blockDump] = BLOCK_SERVO_EXTENDED;
    }

    servoChangeRate[blockDump] = 5;
    servo[blockDump] = BLOCK_SERVO_RETRACTED;
}

void showIRSegment(int dir)
{
    switch (dir) {

    case 5:
       flashGreen();
       break;
    default:
       displayCaution();
       break;
    }
}

int findIRBeacon()
{
    int dir;
    int i;

    for (i = 0; i < 4; i++) {
	    moveBackward(travelDistance[i], 50);
        wait1Msec(500);
        dir = HTIRS2readACDir(IRSeeker);
        showIRSegment(dir);
        nxtDisplayTextLine(2, "Reading %d", dir);

	    if (dir == 5) {
	        return i;
	    }
    }

    return -1;
}

void rangeFind()
{
}

int findIRBeacon_v2()
{
    int acS1, acS2, acS3, acS4, acS5, _dirAC = 0;
    int max = 0;
    bool done;
    int dir;

    tHTIRS2DSPMode _mode = DSP_1200;
    HTIRS2setDSPMode(IRSeeker, _mode);

    moveBackwardOn(50);

    while (!done) {
	    HTIRS2readAllACStrength(IRSeeker, acS1, acS2, acS3, acS4, acS5);
	    dir = HTIRS2readACDir(IRSeeker);
	    if (dir == 5) {
            rangeFind();
        }
    }

    return 0;
}


task main()
{
    int basketNumber;
    bool done = false;

    initializeRobot();

    waitForStart(); // Wait for the beginning of autonomous phase.

    wait1Msec(10000);

    disableDiagnosticsDisplay();
    eraseDisplay();

    basketNumber = findIRBeacon();
    nxtDisplayTextLine(5, "Beacon #%d", basketNumber);

    wait1Msec(300);

    if (basketNumber != -1) {
        if (compensation[basketNumber] < 0) {
            moveForward(abs(compensation[basketNumber]), 60);
        } else {
            moveBackward(compensation[basketNumber], 60);
        }
        /*for (int i = 0; i <= basketNumber; i++) {
            displayCaution();
            wait1Msec(500);
            displayBackward();
            wait1Msec(500);
        }
        displayRestingPulse();
        */
		dumpBlock();
    } else {
        basketNumber = 3;
    }

    //moveToRamp(basketNumber);

    while (true)
    {}
}
