#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#include "../library/auto_defs.h"
#include "../library/sensors/drivers/hitechnic-sensormux.h"
#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../library/sensors/drivers/hitechnic-compass.h"
#include "../library/sensors/drivers/hitechnic-protoboard.h"
#include "../library/DrivetrainSquare.c"
#include "../library/dead_reckon.h"

const tMUXSensor IRSeeker = msensor_S2_4;

#include "../library/light_strip.h"
#include "../library/rnrr_start.h"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initializeRobot()
{
	servo[blockDump] = BLOCK_SERVO_RETRACTED;

    lightStripInit(0x1F);
    displayRestingPulse();

}

task main()
{
    initializeRobot();

    RNRR_waitForStart();

    init_path();
    add_segment(70, 0, 100);
    stop_path();

    dead_reckon();

    while (true) { }
}
