#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IRSeeker,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\FIRST\FTC-Team-25\lib\sensors\drivers\hitechnic-irseeker-v2.h"
#include "C:\FIRST\FTC-Team-25\lib\ir_utils.h"

typedef enum dir_ {
    dir_right,
    dir_left,
    dir_center,
} direction;

direction get_dir_to_beacon() {
	int segment;
	direction dir;

	segment = HTIRS2readACdir(IRSeeker);

	nxtDisplayTextLine(5, "Segment %d", segment);

	switch (segment) {
	case 1:
	case 2:
	case 3:
	case 4:
		dir = dir_left;
		break;
	case 5:
		dir = dir_center;
		break;
	case 6:
	case 7:
	case 8:
	case 9:
		dir = dir_right;
		break;
	}

	return dir;

}

void check_ir_sensor(void)
{
	while (true) {
	  	tHTIRS2DSPMode mode = DSP_1200;
		if (HTIRS2setDSPMode(IRSeeker, mode))
	        break; // Sensor initialized

	    PlaySound(soundShortBlip);
	    nxtDisplayCenteredTextLine(6, "Connect Sensor");
	    nxtDisplayCenteredTextLine(7, "to Port S2");
	    wait1Msec(100);
	}
}

// Entrance to task main().

task main() {

  	// Define variables.
	direction dir;
	int strength;

	check_ir_sensor();

	eraseDisplay();

	while (true) {
	    // Determine where beacon is.
		dir = get_dir_to_beacon();

	    // Determine distance of beacon (strength).

		strength = get_ir_strength(IR_STRENGTH_3);

	    // Display direction and strength on the display.

		nxtDisplayTextLine(3, "Direction %d", dir);
		nxtDisplayTextLine(4, "Strength %d", strength);

		// Turn robot. Move forward until a foot away from
		// beacon. Stop.

		if (dir == dir_right) {
			motor[frontLeft] = -50;
			motor[frontRight] = 50;
		}
		else if (dir == dir_left) {
			motor[frontLeft] = 50;
			motor[frontRight] = -50;
		}
		else if (dir == dir_center) {
			motor[frontLeft] = 50;
			motor[frontRight] = 50;
		}
	}
}
