#pragma config(UserModel, "../pragmas/baemax.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FOUR_WHEEL_DRIVE
#define DEAD_RECKON_GYRO

#include "JoystickDriver.c"
#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/hitechnic-protoboard.h"
#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/sensors/drivers/hitechnic-gyro.h"

const tMUXSensor HTGYRO  = msensor_S4_3;
const tMUXSensor irr_left = msensor_S4_1;
const tMUXSensor irr_right = msensor_S4_2;

bool beacon_done;
int distance_monitor_distance;

#include "../../lib/rnrr_start.h"
#include "../library/baemax_defs.h"
#include "../../lib/baemax_drivetrain_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"
#include "../../lib/us_utils.h"
#include "../../lib/us_cascade_utils.c"
#include "../../lib/limit_switch.h"
#include "../library/auto_utils.h"

const tMUXSensor HTPB = msensor_S4_4;

task ext_dock_arm()
{
    servo[dockarm] = SERVO_DOCK_ARM_FORWARD;
    wait1Msec(2000);
    servo[finger] = SERVO_FINGER_UP;
    wait1Msec(1500);
    servo[dockarm] = SERVO_DOCK_ARM_STOPPED;
}

void initializeRobot()
{
	if (!limit_switch_init(HTPB, 0x05)) {
		nxtDisplayCenteredBigTextLine(3, "ERROR");
		nxtDisplayTextLine(6, "CF251, LP: IZZIE");
	}

    nMotorEncoder[shoulder] = 0;

    servo[dockarm] = SERVO_DOCK_ARM_STOPPED;
    servo[finger] = SERVO_FINGER_UP;
    servo[door] = SERVO_DOOR_CLOSED;
    servo[brush] = 127;
    servo[fist] = 25;

    motor[shoulder] = 0;

    move_to(arm_motor, 60, 10251);
}

task main()
{
    initializeRobot();
    RNRR_waitForStart();      // Wait for the beginning of autonomous phase.

    init_path();
    add_segment(-83, 0, 30);  // Gets off the ramp to medium goal
    stop_path();
    dead_reckon();

    raise_shoulder(shoulder, 35, 10, 2500);
    wait1Msec(2000);

    servo[door] = SERVO_DOOR_OPEN;
    servo[brush] = 255;
    wait1Msec(10000);
    servo[brush] = 127;

    while (true){
    }
}
