#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     carrot,         sensorSONAR)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C2_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     driveFrontRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     shoulder,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     driveFrontLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    brush,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    arm,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    dockarm,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_1,    rightEye,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    leftEye,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    finger,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    door,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FOUR_WHEEL_DRIVE
#define DEAD_RECKON_GYRO

#include "JoystickDriver.c"
#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/sensors/drivers/hitechnic-gyro.h"

const tMUXSensor HTGYRO  = msensor_S4_3;

#include "../library/baemax_defs.h"
#include "../../lib/baemax_drivetrain_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"
#include "../../lib/us_utils.h"
#include "../../lib/us_cascade_utils.c"
#include "../library/auto_utils.h"

const tMUXSensor irr_left = msensor_S4_1;
const tMUXSensor irr_right = msensor_S4_2;

ir_direction_t dir;

void move_to_pole(int count)                 // Function that moves the robot to the pole
{                                            // based on the position of the center goal.
    init_path();

    switch (count) {
    case 1:
        add_segment(-25, 0, 50);
        add_segment(0, 45, 100);
        add_segment(-5, -45, 100);
        add_segment(0, 45, 100);
        add_segment(-5, -45, 100);
        add_segment(0, 45, 100);
        add_segment(-5, -45, 100);
        add_segment(0, 45, 100);
        break;
    case 2:
        add_segment(-13, 0, 50);
        add_segment(-50, 30, 100);
        add_segment(4, 20, 100);
        break;
    case 3:
        add_segment(-10, 90, 50);
        add_segment(-45, -90, 100);
        break;
    }
    stop_path();
  	dead_reckon();
}

void raise_arm()
{
    motor[shoulder] = 30;
    while (nMotorEncoder[shoulder] < UPCOUNTS) {        // While encoder counts is less than UPCOUNTS, move shoulder at 15
    }                                                   // power. When encoder counts surpasses UPCOUNTs, stop shoulder.
    motor[shoulder] = 0;

    servoChangeRate[arm] = 0;
    servo[arm] = SERVO_ARM_EXTENDED;                    // Move the arm to the extended position.

    wait1Msec(12000);
}

task main()
{
    int i;
    int center_position;
    int offset;
    int bias;

    bias = HTGYROstartCal(HTGYRO);
    offset = initialize_receiver(irr_left, irr_right);

    servo[arm] = 50;
    servo[leftEye] = LSERVO_CENTER;
    servo[rightEye] = RSERVO_CENTER;
    servo[door] = SERVO_DOOR_CLOSED;
    servo[brush] = 127;

    //waitForStart();

    center_position = ultrasound(carrot, -24, US_DIST_POS_1, US_DIST_POS_3);    // Sets the value integer center_position to 1, 2, or 3
                                                                                // based on ultrasound sensor readings.
    //for (i = 0; i < center_position; i++) {
    //    playImmediateTone(251, 25);                                             // Beep the center structure position for 0.25 second.
    //    wait1Msec(750);
    //}

    if (center_position == 3) {
        raise_arm();

        servo[leftEye] = LSERVO_CENTER + CROSSEYED;
        servo[rightEye] = RSERVO_CENTER - CROSSEYED;

        move_to_beacon_mux(irr_left, irr_right, -10, true);
        score_center_goal(35, 29);
    } else {
        move_to_pole(center_position);
    }

    while(true) {
        nxtDisplayTextLine(1, "Sensor value: %d", SensorValue[carrot]);
    }
}
