#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     carrot,         sensorNone)
#pragma config(Sensor, S3,     irr_left,       sensorI2CCustom)
#pragma config(Sensor, S4,     irr_right,      sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C2_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     driveFrontRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     shoulder,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     driveFrontLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    finger,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    brush,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    arm,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    dockarm,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_1,    centerDispenser,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    leftEye,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    rightEye,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define FOUR_WHEEL_DRIVE
#define LSERVO_CENTER               134
#define RSERVO_CENTER               113
#define RSERVO_PERP                 235

#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/drivetrain_andymark_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"

#define SERVO_ARM_EXTENDED          90
#define SERVO_ARM_RETRACTED         150
#define SERVO_ARM_EXTENDED_HALF     120
#define SERVO_ARM_PICKUP            140

#define SERVO_DOCK_ARM_FORWARD      80
#define SERVO_DOCK_ARM_BACKWARD     0
#define SERVO_DOCK_ARM_STOPPED      127
#define SERVO_FINGER_UP             160
#define SERVO_FINGER_DOWN           146


task ext_dock_arm()
{
    servo[dockarm] = SERVO_DOCK_ARM_FORWARD;
    wait1Msec(2000);
    servo[finger] = SERVO_FINGER_UP;
    wait1Msec(1500);
    servo[dockarm] = SERVO_DOCK_ARM_STOPPED;
}

void initializeRobot()
{
    servo[arm] = SERVO_ARM_RETRACTED;
    servo[finger] = SERVO_FINGER_DOWN;
}

task main()
{
  initializeRobot();

  waitForStart();                           // Wait for the beginning of autonomous phase.

    init_path();
    add_segment(-49, 0, 30);                //off ramp
    stop_path();
    dead_reckon();

    startTask(ext_dock_arm);

    init_path();
    add_segment(-34, 0, 40);                //going to the pole tower thing
    stop_path();
    dead_reckon();

    servo[finger] = SERVO_FINGER_DOWN;
    servo[dockarm] = SERVO_DOCK_ARM_BACKWARD;
    wait1Msec(4000);
    servo[dockarm] = SERVO_DOCK_ARM_STOPPED;

    init_path();
    add_segment(9, 45, 20);
    add_segment(83, 315, 30);               // going back on ramp to drop off the goal
    stop_path();
    dead_reckon();

    servo[finger] = SERVO_FINGER_UP;
    servo[dockarm] = SERVO_DOCK_ARM_BACKWARD;
    wait1Msec(2000);
    servo[dockarm] = SERVO_DOCK_ARM_STOPPED;

    init_path();
    add_segment(-50, 0, 40);               // going back off the ramp

    while (true){
    }
}
