#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     irrLeft,        sensorI2CCustom)
#pragma config(Sensor, S3,     irrRight,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/drivetrain_andymark_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"

ir_direction_t dir;

void move_to_position(int position)
{
    init_path();

    switch (position) {
    case 1:
        add_segment(18, 0, 50);     // Move robot to position one.
        break;
    case 2:
        add_segment(30, -45, 50);   // Move robot to position two.
	    add_segment(0, 90, 25);
        break;
    case 3:
        add_segment(15, -90, 50);   // Move robot to position three.
        add_segment(0, 135, 25);
        break;

    stop_path();
    dead_reckon();
    }
}

task main()
{
    // initialize_receiver(irrLeft, irrRight);

    int i;
	for (i = 1; i < 4; i++) {
	    move_to_position(i);
	    dir = get_dir_to_beacon(irrLeft);

	    if (dir == DIR_CENTER) {
            break;
	    }
	}
	move_to_beacon(irrLeft, irrRight, 35, true);
}
