#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef enum dir_ {                                        // Define enumerations for direction.
    right,
    left,
    center,
} direction;

	direction get_dir_to_beacon(void) {
    int segment;
	segment = HTIRS2readACdir(irSensor);
	}

direction dir;

switch(segment) {										   // Use switch statement to define the
	case 1:												   // IR Sensor values to a certain dir-
	case 2:												   // ection.
	case 3:
	case 4:
		dir = left;
		break;

	case 5:
		dir = center;
		break;

	case 6:
	case 7:
	case 8:
	case 9:
		dir = right;
		break;
}

return dir;

task main() {
    direction dir;

    while(true) {
        dir = get_dir_to_beacon;

		switch (dir) {
            case left:
            nxtDisplayTextLine(4, "The target is to the left.");
			break;

            case center:
            nxtDisplayTextLine(4, "The target is in front of me.");
			break;

            case right:
            nxtDisplayTextLine(4, "The target is to the right.");
            break;

            default:
            nxtDisplayTextLine(4, "I don't know where the target is.");
		}
	}
}
