#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearLeft, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     driveFrontLeft, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     driveFrontRight, tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FOUR_WHEEL_DRIVE

#include "C:\FIRST\FTC-Team-25\lib\drivetrain_defs.h"
#include "C:\FIRST\FTC-Team-25\lib\drivetrain_square.h"
#include "C:\FIRST\FTC-Team-25\lib\dead_reckon.h"

task main()
{
	init_path();

	add_segment(70, 0, 50);    // Move robot off ramp.
	add_segment(0, -90, 25);   // Turn towards goal.
	add_segment(-2, 0, 50);    // Align against wall.
	add_segment(40, 0, 50);    // Move towards goal.
	while(true) {
	PlayImmediateTone(251, 50);   // Play tone of frequency 251 for 0.5 seconds.
 	wait1Msec(500);               // Wait for 0.5 seconds.
	}

	add_segment(0, -45, 0);    // Turn 45 degrees left.
	add_segment(32.5, 0, 0);   // Move to position 2.
	add_segment(0, 135, 0);    // Turn towards position 2.
	while(true) {
	PlayImmediateTone(251, 50);   // Play tone of frequency 251 for 0.5 seconds.
 	wait1Msec(500);               // Wait for 0.5 seconds.
	}

	add_segment(-2, 0, 0);     // Move backwards.
	add_segment(0, -45, 0);    // Turn 45 degrees left.
	add_segment(37, 0, 0);     // Move to position 3.
	add_segment(0, 45, 0);     // Turn towards position 3.
	while(true) {
	PlayImmediateTone(251, 50);   // Play tone of frequency 251 for 0.5 seconds.
 	wait1Msec(500);               // Wait for 0.5 seconds.
	}

	stop_path();
	dead_reckon();
}
