#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\FIRST\FTC-Team-25\lib\drivetrain_andymark_defs.h"
#include "C:\FIRST\FTC-Team-25\lib\drivetrain_square.h"
#include "C:\FIRST\FTC-Team-25\lib\dead_reckon.h"

task main()
{
	init_path();

	add_segment(-70, 0, 50);

	stop_path();
	dead_reckon();
}
