#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
TETRIX Scissorbot - Basic IR Beacon Tracking
- NOTE: Scissorbot is best at picking up rings when the gripper PARALLEL to the ring.
- This program causes the robot to drive toward the IR Beacon using its IR Seeker sensor, forever.
- Use the "View Sensors" button in the bottom-right of the virtual window to visualize the IR beam!
- The IR Seeker reads values 0-9 and has a 240 degree field of view.
	- 0: Sensor does not see the beacon
	- 1-4: Sensor detects the beacon on the left side
	- 5: Sensor is directly aligned witht he beacon
	- 6-9: Sensor detects the beacon on the right side
----------------------------------------------------------------------------------------------------*/

task main()
{
	//Variable that keeps track of the last IR Seeker value.
	int lastValue = 0;

	//Loop Forever
	while(1 == 1)
	{
		if(SensorValue[IRSeeker] > 5)	//If the right side of the sensor detects the beacon...
		{
			//...turn left.
			lastValue = SensorValue[IRSeeker];
			motor[motorD] = -35;
			motor[motorF] = -35;
			motor[motorE] = 35;
			motor[motorG] = 35;
		}
		else if(SensorValue[IRSeeker] < 5)	//If the left side of the sensor detects the beacon (or doesn't see it)...
		{
			//...turn right.
			lastValue = SensorValue[IRSeeker];
			motor[motorD] = 35;
			motor[motorF] = 35;
			motor[motorE] = -35;
			motor[motorG] = -35;
		}
		else if(SensorValue[IRSeeker] == 5)	//If the sensor is lined up with the beacon...
		{
			//...drive straight.
			lastValue = SensorValue[IRSeeker];
			motor[motorD] = 50;
			motor[motorF] = 50;
			motor[motorE] = 50;
			motor[motorG] = 50;
		}
	}
}
