#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Light Sensor Values for the different colored surfaces
	int blueValue = 41;
	int redValue = 37;
	int whiteValue = 88;
	int blackValue = 20;
	int grayValue = 42;

	//Move Forward until the light sensor detects one of the colors
	while(SensorValue[lightSensor] != blueValue)
	{
		motor[motorD] = 50;
		motor[motorE] = 50;
	}

	//Stop
	motor[motorD] = 0;
	motor[motorE] = 0;
}
