#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irr,            sensorI2CCustom)
#pragma config(Sensor, S3,     irr_left,       sensorNone)
#pragma config(Sensor, S4,     carrot,         sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    leftEye,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LSERVO_ANGLE  70

#define DEAD_RECKON_GYRO

#include "../../lib/sensors/drivers/hitechnic-sensormux.h"

#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/hitechnic-protoboard.h"
#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/sensors/drivers/hitechnic-gyro.h"

const tMUXSensor HTGYRO  = msensor_S4_3;
//const tMUXSensor irr_left = msensor_S4_1;
//const tMUXSensor irr_right = msensor_S4_2;

bool beacon_done;
int distance_monitor_distance;

// include "../library/auto_utils.h"

task main()
{
    int i;
    int segment;

    i = 0;

    servo[leftEye] = 44;

    wait1Msec(500);

    segment = HTIRS2readACDir(irr);
    while (segment != 6) {
        nxtDisplayCenteredBigTextLine(4, "%d %d", segment, i);
        if (segment > 6) {
            motor[driveRearRight] = -1;
            motor[driveRearLeft] = 1;
        } else {
            motor[driveRearRight] = 1;
            motor[driveRearLeft] = -1;
        }
        segment = HTIRS2readACDir(irr);
    }
    motor[driveRearRight] = 0;
    motor[driveRearLeft] = 0;

    while(true) {
        segment = HTIRS2readACDir(irr);
        nxtDisplayCenteredBigTextLine(4, "%d %d", segment, i);
    }
}
