#pragma config(UserModel, "../pragmas/baemax.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FOUR_WHEEL_DRIVE
#define DEAD_RECKON_GYRO

#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/hitechnic-protoboard.h"
#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/sensors/drivers/hitechnic-gyro.h"

const tMUXSensor HTGYRO  = msensor_S4_3;
bool beacon_done;
int distance_monitor_distance;

#include "../library/baemax_defs.h"
#include "../../lib/baemax_drivetrain_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"
#include "../../lib/us_utils.h"
#include "../../lib/us_cascade_utils.c"
#include "../../lib/limit_switch.h"
#include "../library/auto_utils.h"

const tMUXSensor irr_left = msensor_S4_1;
const tMUXSensor irr_right = msensor_S4_2;
const tMUXSensor HTPB = msensor_S4_4;

task main()
{
	int ls1, ls2, ls3, ls4, ls5 = 0;
	int rs1, rs2, rs3, rs4, rs5 = 0;
    int ldir, rdir;

    servo[leftEye] = LSERVO_CENTER + CROSSEYED;
    servo[rightEye] = RSERVO_CENTER - CROSSEYED;

	while (true) {
	    HTIRS2readAllACStrength(irr_left, ls1, ls2, ls3, ls4, ls5);
	    HTIRS2readAllACStrength(irr_right, rs1, rs2, rs3, rs4, rs5);
	    ldir = HTIRS2readACDir(irr_left);
        rdir = HTIRS2readACDir(irr_right);
	    nxtDisplayCenteredBigTextLine(2, "L: %d: %d", ls3, ldir);
	    nxtDisplayCenteredBigTextLine(4, "R: %d: %d", rs3, rdir);
    }
    while (true) {}
}
