#pragma config(UserModel, "../pragmas/baemax.h")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FOUR_WHEEL_DRIVE
#define DEAD_RECKON_GYRO

#include "../../lib/sensors/drivers/hitechnic-sensormux.h"

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/hitechnic-protoboard.h"
#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/sensors/drivers/hitechnic-gyro.h"

const tMUXSensor HTGYRO  = msensor_S4_3;
bool beacon_done;
int distance_monitor_distance;

#include "../../lib/limit_switch.h"

const tMUXSensor irr_left = msensor_S4_1;
const tMUXSensor irr_right = msensor_S4_2;
const tMUXSensor HTPB = msensor_S4_4;

task main()
{
	if (!limit_switch_init(HTPB, 0x05)) {
		goto _err;
	}

	while (true) {
		if (is_limit_switch_closed(0x05)) {
			nxtDisplayCenteredBigTextLine(2, "Closed");
		} else {
			nxtDisplayCenteredBigTextLine(2, "Open");
		}
        if (is_limit_switch_closed(0x04)) {
            nxtDisplayCenteredBigTextLine(5, "Closed");
        } else {
            nxtDisplayCenteredBigTextLine(5, "Open");
        }
	}

_err:
	while (true) {}
}
