#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     compass,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\library\sensors\drivers\hitechnic-compass.h"

bool done;

task rotate()
{
	motor[driveRearRight] = 10;
	motor[driveRearLeft] = -10;
	wait1Msec(40000);
	motor[driveRearRight] = 0;
	motor[driveRearLeft] = 0;
    done = true;
}

task main()
{
    done = false;

	eraseDisplay();

    nMotorEncoder[driveRearRight] = 0;
    nMotorEncoder[driveRearLeft] = 0;

	HTMCstartCal(compass);
	StartTask(rotate);

    while (!done) {
        nxtDisplayTextLine(2, "Right: %d", nMotorEncoder[driveRearRight]);
        nxtDisplayTextLine(3, "Left:  %d", nMotorEncoder[driveRearLeft]);
    }
	HTMCstopCal(compass);

    while (true) {}
}
