#pragma config(UserModel, "../pragmas/baemax.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encodercounts;

bool debounce;

task debounceTask()
{
    debounce = true;
    wait1Msec(500);
    debounce = false;
}

task main()
{
	debounce = false;

	nMotorEncoder[arm_motor] = 0;

    encodercounts = 0;

    while (true) {
    	if (!debounce) {
	        if (nNxtButtonPressed == 1) {
		        encodercounts = encodercounts + 50;

		        motor[arm_motor] = 25;
				while (nMotorEncoder[arm_motor] < encodercounts) {
					nxtDisplayCenteredBigTextLine(3, "%d", encodercounts);
				}
				motor[arm_motor] = 0;

				startTask(debounceTask);
			} else if (nNxtButtonPressed == 2) {
	            encodercounts = encodercounts - 50;

	            motor[arm_motor] = -25;
			    while (nMotorEncoder[arm_motor] > encodercounts) {
			    	nxtDisplayCenteredBigTextLine(3, "%d", encodercounts);
			    }
			    motor[arm_motor] = 0;

			    startTask(debounceTask);
	    	}
		}
    }
}
