#pragma config(UserModel, "../pragmas/baemax.h")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SERVO_MAX 255
#define SERVO_MIN 0

bool done;
tSensors link;

task calibrateServo()
{
    int val;

    while (!done) {
	    val = ServoValue[link];
        servo[link] = --val;
		nxtDisplayCenteredBigTextLine(4, "%d", val);
        wait1Msec(300);
    }
}

task main()
{
    link = door;

    done = false;
    servoChangeRate[link]  = 5;

    // servo[link] = SERVO_MAX/2;
    servo[link] = 128;

    wait1Msec(1000);

    startTask(calibrateServo);

    while (1) {
        if (nNxtButtonPressed == 3) {
            done = true;
        }
    }

    while(1) {}
}
