#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    finger,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    arm,                  tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FINGER_UP   110
#define FINGER_DOWN 173

task main()
{
    static bool up = false;
    servo[finger] = FINGER_DOWN;
    while (true) {
        if (nNxtButtonPressed == 3) {
            up = !up;
            if (up)
                servo[finger] = FINGER_UP;
            else
                servo[finger] = FINGER_DOWN;
        }
    }

    while (true) {
    }
}
