#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     irr_right,      sensorI2CCustom)
#pragma config(Sensor, S3,     irr_left,       sensorI2CCustom)
#pragma config(Sensor, S4,     carrot,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    leftEye,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    rightEye,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LSERVO_CENTER 134
#define LSERVO_ANGLE  70
#define RSERVO_CENTER 113
#define RSERVO_PERP   235

#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/drivetrain_andymark_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"

ir_direction_t dir;

int count;
int position;

void move_to_pole(int count)
{
    init_path();

    switch (count) {
    case 1:
        add_segment(26, 15, 45);
        add_segment(-7.5, 105, 80);
        break;
    case 2:
        add_segment(22, 0, 45);
        add_segment(-7.5, -135, 50);
        break;
    case 3:
        add_segment(27, 27.5, 45);
        add_segment(-13.5, -202, 50);
        break;
    }
    stop_path();
  	dead_reckon();
}

task main()
{
    int i;

    servo[leftEye] = LSERVO_CENTER;
    servo[rightEye] = RSERVO_CENTER;

    init_path();
    add_segment(24, 0, 50);                     // Move to beacon sensing position.
    stop_path();
    dead_reckon();

    if (SensorValue[carrot] < 60) {
        position = 3;
    } else if (SensorValue[carrot] < 80) {        // If ultrasonic sensor sees a position,
        position = 1;                             // set variable "position" to position number.
    } else {
        position = 2;
    }

    move_to_pole(position);                     // Move to pole using position number.

    for (i = 0; i < position; i++) {            // Beep for the position number that the
        playImmediateTone(251, 50);             // ultrasonic sensor sees.
        wait1Msec(1000);
    }
}
