#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     irr_right,      sensorI2CCustom)
#pragma config(Sensor, S3,     irr_left,       sensorI2CCustom)
#pragma config(Sensor, S4,     carrot,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    leftEye,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    rightEye,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LSERVO_ANGLE  70

#define DEAD_RECKON_GYRO

#include "../../lib/sensors/drivers/hitechnic-sensormux.h"

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/hitechnic-protoboard.h"
#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/sensors/drivers/hitechnic-gyro.h"

const tMUXSensor HTGYRO  = msensor_S4_3;
//const tMUXSensor irr_left = msensor_S4_1;
//const tMUXSensor irr_right = msensor_S4_2;

bool beacon_done;
int distance_monitor_distance;

#include "../library/baemax_defs.h"
#include "../../lib/baemax_drivetrain_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/limit_switch.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"
#include "../../lib/us_utils.h"
#include "../../lib/button_utils.h"
#include "../../lib/us_cascade_utils.c"
// include "../library/auto_utils.h"

const tMUXSensor HTPB = msensor_S4_4;

ir_direction_t dir;

int count;
int beep;

void move_to_position(int position)
{
	init_path();

	switch (position) {
	case 1:
        add_segment(53.5, -30, 40);
        add_segment(0, 120, 40);
        break;
    case 2:
        add_segment(40, -90, 40);
        add_segment(0, 145, 40);
        break;
    case 3:
        add_segment(3, 0, 20);
        break;
    }
    stop_path();
  	dead_reckon();
}

task main()
{
    int i;

    servo[leftEye] = LSERVO_CENTER;
    servo[rightEye] = RSERVO_CENTER;

    init_path();
    add_segment(24, 0, 50);                     // Move to beacon sensing position.
    stop_path();
    dead_reckon();

    if (SensorValue[carrot] < 60) {
        beep = 3;
    } else if (SensorValue[carrot] < 80) {      // If ultrasonic sensor sees a position,
        beep = 1;                               // set variable "beep" to position number.
    } else {
        beep = 2;
    }

    move_to_position(beep);                             // Move to center goal using position number.
    move_to_beacon(irr_left, irr_right, 20, true);      // Move relatively in front of the beacon.
    move_to_object(carrot, 5, 16);                      // Go forward until ultrasonic sensor sees certain distance.

    for (i = 0; i < beep; i++) {                // Beep for the position number that the
        playImmediateTone(251, 50);             // ultrasonic sensor sees.
        wait1Msec(1000);
    }

    nxtDisplayTextLine(3, "Sensor sees %d", SensorValue[carrot]);       // Display ultrasonic sensor value.
    while(true) {
    }
}
