#pragma config(UserModel, "../pragmas/baemax.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FOUR_WHEEL_DRIVE
#define DEAD_RECKON_GYRO

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../../lib/sensors/drivers/hitechnic-gyro.h"
#include "../../lib/sensors/drivers/hitechnic-protoboard.h"

const tMUXSensor HTGYRO  = msensor_S4_3;

bool beacon_done;
int distance_monitor_distance;

#include "../library/baemax_defs.h"
#include "../../lib/baemax_drivetrain_defs.h"
#include "../../lib/drivetrain_square.h"
#include "../../lib/dead_reckon.h"
#include "../../lib/data_log.h"
#include "../../lib/ir_utils.h"
#include "../../lib/us_utils.h"
#include "../../lib/us_cascade_utils.c"
#include "../../lib/limit_switch.h"
#include "../library/auto_utils.h"

const tMUXSensor irr_left = msensor_S4_1;
const tMUXSensor irr_right = msensor_S4_2;
const tMUXSensor HTPB = msensor_S4_4;

task main()
{

    disableDiagnosticsDisplay();
    eraseDisplay();

	if (!limit_switch_init(HTPB, 0x04)) {
		nxtDisplayCenteredBigTextLine(4, "Switch Error");
	}

	nMotorEncoder[shoulder] = 0;
    if (is_limit_switch_closed(0x04)) {
        motor[shoulder] = -25;
        while (abs(nMotorEncoder[shoulder]) < 200) {
        }
        motor[shoulder] = 0;
    } else {
		nMotorEncoder[shoulder] = 0;
		motor[shoulder] = -40;
		while (is_limit_switch_open(0x04)) {
			if (abs(nMotorEncoder[shoulder]) < 2600) {
				motor[shoulder] = -10;
			}
			nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[shoulder]);
		}
		motor[shoulder] = 0;
    }
}
