#pragma config(UserModel, "../pragmas/baemax.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	nMotorEncoder[shoulder] = 0;

	motor[shoulder] = -10;
	while (nMotorEncoder[shoulder] > -4000) {
		nxtDisplayTextLine(2, "%d", nMotorEncoder[shoulder]);
		nxtDisplayTextLine(3, "Goin' down.");
		nxtDisplayTextLine(4, "- Megan.");
		nxtDisplayTextLine(5, "(the aubuilogrammer.)");
	}
	motor[shoulder] = 0;
}
