#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     driveRearRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     driveFrontRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     elbow,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     driveFrontLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     driveRearLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    finger,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    brush,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    arm,                  tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define SERVO_ARM_UP    0
#define SERVO_ARM_DOWN  0

static int drive_multiplier = 1;

typedef enum brush_state_ {
    BRUSH_OFF,
    BRUSH_FORWARD,
    BRUSH_BACKWARD,
} brush_state_t;

typedef enum arm_state_ {
    ARM_UP,
    ARM_DOWN,
} arm_state_t;

typedef enum joystick_event_ {
    RIGHT_TRIGGER_UP = 6,
    RIGHT_TRIGGER_DOWN = 8,
    LEFT_TRIGGER_UP = 5,
    LEFT_TRIGGER_DOWN = 7,
    BUTTON_ONE = 1,
    BUTTON_FOUR = 4,
} joystick_event_t;

brush_state_t brush_state;
arm_state_t arm_state;

bool debounce;

task debounceTask()
{
    debounce = true;
    wait1Msec(500);
    debounce = false;
}

void all_stop()
{
    motor[driveFrontLeft] = 0;
    motor[driveRearLeft] = 0;
    motor[driveFrontRight] = 0;
    motor[driveRearRight] = 0;
}

void brush_enter_state(brush_state_t state)
{
    brush_state = state;

    switch (state) {
    case BRUSH_OFF:
        servo[brush] = 127;
        break;
    case BRUSH_FORWARD:
        servo[brush] = 5;
        break;
    case BRUSH_BACKWARD:
        servo[brush] = 250;
        break;
    }
}

void arm_enter_state(arm_state_t state)
{
    arm_state = state;

    switch (state) {
    case ARM_UP:
        servo[arm] = SERVO_ARM_UP;
        break;
    case ARM_DOWN:
        servo[arm] = SERVO_ARM_DOWN;
        break;
    }
}

void initializeRobot()
{
    brush_enter_state(BRUSH_OFF);
    arm_enter_state(ARM_DOWN);

    all_stop();

    return;
}

void handle_joy1_btn1()
{
    switch (brush_state) {
    case BRUSH_FORWARD:
        brush_enter_state(BRUSH_OFF);
        break;
    case BRUSH_BACKWARD:
        brush_enter_state(BRUSH_FORWARD);
        break;
    case BRUSH_OFF:
        brush_enter_state(BRUSH_FORWARD);
        break;
    }
}

void handle_joy1_btn4()
{
    switch (brush_state) {
    case BRUSH_FORWARD:
        brush_enter_state(BRUSH_BACKWARD);
        break;
    case BRUSH_BACKWARD:
        brush_enter_state(BRUSH_OFF);
        break;
    case BRUSH_OFF:
        brush_enter_state(BRUSH_BACKWARD);
        break;
    }
}

void handle_joy1_event(joystick_event_t event)
{
    switch (event) {
    case BUTTON_ONE:
        handle_joy1_btn1();
        break;
    case BUTTON_FOUR:
        handle_joy1_btn4();
        break;
    }

    startTask(debounceTask);
}

task main()
{
    short right_y;
    short left_y;

    debounce = false;

    initializeRobot();

    waitForStart();   // wait for start of tele-op phase

    // StartTask(endGameTimer);

    while (true) {

        getJoystickSettings(joystick);

        if (!debounce) {
	        if (joy1Btn(Btn1)) {
	            handle_joy1_event(BUTTON_ONE);
	        } else if (joy1Btn(Btn4)) {
	            handle_joy1_event(BUTTON_FOUR);
	        }
        }

        //if (drive_multiplier) {
            //right_y = joystick.joy1_y2;
            //left_y = joystick.joy1_y1;
        //} else {
            right_y = joystick.joy1_y1;
            left_y = joystick.joy1_y2;
        //}

        if (abs(right_y) > 20) {
	    	motor[driveFrontRight] = drive_multiplier * right_y;
	    	motor[driveRearRight] = drive_multiplier * right_y;
		}
		else {
		    motor[driveFrontRight] = 0;
		    motor[driveRearRight] = 0;
		}

        if (abs(left_y) > 20) {
		    motor[driveFrontLeft] = drive_multiplier * left_y;
		    motor[driveRearLeft] = drive_multiplier * left_y;
		}
		else
		{
		    motor[driveFrontLeft] = 0;
		    motor[driveRearLeft] = 0;
		}
    }
}
