#pragma config(UserModel, "../pragmas/monkey.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "../../lib/sensors/drivers/hitechnic-sensormux.h"
#include "../../lib/sensors/drivers/lego-ultrasound.h"

// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

const tMUXSensor LEGOUS = msensor_S3_2;

#define RIGHT_FANG_STOW		    0
#define RIGHT_FANG_DEPLOY		208
#define LEFT_FANG_STOW		    240
#define LEFT_FANG_DEPLOY		20

#define RIGHT_GUIDE_STOW    195
#define RIGHT_GUIDE_DEPLOY  100
#define LEFT_GUIDE_STOW     75
#define LEFT_GUIDE_DEPLOY   190

#define RAMP_TILT       50
#define RAMP_PICKUP     875

#define RAMP_SPEED_UP              -30
#define RAMP_SPEED_DOWN             30
#define SHOULDER_SPEED_UP           60
#define SHOULDER_SPEED_DOWN        -10

#define SERVO_ROLLER_UP             25
#define SERVO_ROLLER_OSC_DOWN       80
#define SERVO_ROLLER_DOWN           137

#define SERVO_AUTOELBOW_UP          37
#define SERVO_AUTOELBOW_DOWN        233


#define CONVEYOR_POWER              100
#define LSERVO_DOCK_FINGER_STOWED   82
#define LSERVO_DOCK_FINGER_UP       205
#define LSERVO_DOCK_FINGER_DOWN     161
#define RSERVO_DOCK_FINGER_STOWED   144
#define RSERVO_DOCK_FINGER_UP       0
#define RSERVO_DOCK_FINGER_DOWN     64

static int drive_multiplier = 1;

bool deadman_ltu_running;
bool deadman_ltd_running;
bool deadman_rtu_running;
bool deadman_rtd_running;

typedef enum conveyor_state_ {
    CONVEYOR_OFF,
    CONVEYOR_FORWARD,
    CONVEYOR_BACKWARD,
} conveyor_state_t;

typedef enum shoulder_state_ {
    SHOULDER_STOP,
    SHOULDER_UP,
    SHOULDER_DOWN,
} shoulder_state_t;
/*
typedef enum ramp_state_ {
    RAMP_UP,
    RAMP_DOWN,
    RAMP_STOP,
} ramp_state_t;
*/
typedef enum joystick_event_ {
    RIGHT_TRIGGER_UP = 6,
    RIGHT_TRIGGER_DOWN = 8,
    LEFT_TRIGGER_UP = 5,
    LEFT_TRIGGER_DOWN = 7,
    BUTTON_ONE = 1,
    BUTTON_TWO = 2,
    BUTTON_THREE = 3,
    BUTTON_FOUR = 4,
    BUTTON_TEN	= 10,
} joystick_event_t;

conveyor_state_t conveyor_state;
//ramp_state_t ramp_state;
shoulder_state_t shoulder_state;

bool debounce;

task debounceTask()
{
    debounce = true;
    wait1Msec(500);
    debounce = false;
}

void push_ball()
{
	int i;

    for (i = SERVO_ROLLER_UP; i <= SERVO_ROLLER_OSC_DOWN; i++) {
        servo[roller] = i;
        wait1Msec(10);
    }
    servo[roller] = SERVO_ROLLER_UP;
}

task ball_watch()
{
    int dist;
    int i;
    int ball_count;

    ball_count = 0;
    nxtDisplayCenteredBigTextLine(2, "%d", ball_count);

    while (true) {
        dist = USreadDist(LEGOUS);
        if (dist <= 7) {
            // eraseDisplay();
            nxtDisplayCenteredBigTextLine(2, "%d", ++ball_count);

            wait1Msec(2000);

            playImmediateTone(60, 100);

			push_ball();

            wait1Msec(1000);
        }
    }
}

void shoulder_enter_state(shoulder_state_t state)
{
    shoulder_state = state;

    switch (state) {
    case SHOULDER_UP:
        motor[elbow] = SHOULDER_SPEED_UP;
        motor[elbow] = SHOULDER_SPEED_UP;
        break;
    case SHOULDER_DOWN:
        motor[elbow] = SHOULDER_SPEED_DOWN;
        motor[elbow] = SHOULDER_SPEED_DOWN;
        break;
    case SHOULDER_STOP:
        motor[elbow] = 0;
        motor[elbow] = 0;
        break;
    }
}
/*
void ramp_enter_state(ramp_state_t state)
{
    ramp_state = state;

    switch (state) {
    case RAMP_UP:
        motor[motorA] = RAMP_SPEED_UP;
        motor[motorB] = RAMP_SPEED_UP;
        break;
    case RAMP_DOWN:
        motor[motorA] = RAMP_SPEED_DOWN;
        motor[motorB] = RAMP_SPEED_DOWN;
        break;
    case RAMP_STOP:
        motor[motorA] = 0;
        motor[motorB] = 0;
        break;
    }
}
*/
task deadman_ltu()
{
    if (!deadman_ltd_running) {
	    deadman_ltu_running = true;
	    shoulder_enter_state(SHOULDER_UP);

	    while ((joy1Btn(Btn5)) && (deadman_ltd_running == false)) {
	    }

	    shoulder_enter_state(SHOULDER_STOP);
	    deadman_ltu_running = false;
    }
}

task deadman_ltd()
{
    if (!deadman_ltu_running) {
	    deadman_ltd_running = true;
	    shoulder_enter_state(SHOULDER_DOWN);

	    while ((joy1Btn(Btn7)) && (deadman_ltu_running == false)) {
	    }

	    shoulder_enter_state(SHOULDER_STOP);
	    deadman_ltd_running = false;
    }
}

void all_stop()
{
    motor[driveFrontLeft] = 0;
    motor[driveRearLeft] = 0;
    motor[driveFrontRight] = 0;
    motor[driveRearRight] = 0;
}


void conveyor_enter_state(conveyor_state_t state)
{
    conveyor_state = state;

    switch (state) {
    case CONVEYOR_OFF:
        motor[conveyor] = 0;
        break;
    case CONVEYOR_FORWARD:
        motor[conveyor] = CONVEYOR_POWER;
        break;
    case CONVEYOR_BACKWARD:
        motor[conveyor] = -CONVEYOR_POWER;
        break;
    }
}

task validate_conveyor()
{
    while (true) {
        conveyor_enter_state(CONVEYOR_OFF);
        wait1Msec(100);
        conveyor_enter_state(CONVEYOR_FORWARD);
        wait1Msec(10000);
    }
}

void initializeRobot()
{
    bFloatDuringInactiveMotorPWM = false;

    deadman_ltu_running = false;
    deadman_ltd_running = false;
    deadman_rtu_running = false;
    deadman_rtd_running = false;

    conveyor_enter_state(CONVEYOR_OFF);
    //ramp_enter_state(RAMP_STOP);

    servo[roller] = SERVO_ROLLER_DOWN;
	servo[leftGoalGuide] = LEFT_GUIDE_STOW;
	servo[rightGoalGuide] = RIGHT_GUIDE_STOW;
	servo[leftFang] = LEFT_FANG_STOW;
	servo[rightFang] = RIGHT_FANG_STOW;

    servo[autoElbow] = 233;

    all_stop();

    return;
}

void handle_joy1_btn1()
{
    switch (conveyor_state) {
    case CONVEYOR_FORWARD:
        conveyor_enter_state(CONVEYOR_OFF);
        break;
    case CONVEYOR_BACKWARD:
        conveyor_enter_state(CONVEYOR_FORWARD);
        break;
    case CONVEYOR_OFF:
        conveyor_enter_state(CONVEYOR_FORWARD);
        break;
    }
}

void handle_joy1_btn4()
{
    switch (conveyor_state) {
    case CONVEYOR_FORWARD:
        conveyor_enter_state(CONVEYOR_BACKWARD);
        break;
    case CONVEYOR_BACKWARD:
        conveyor_enter_state(CONVEYOR_OFF);
        break;
    case CONVEYOR_OFF:
        conveyor_enter_state(CONVEYOR_BACKWARD);
        break;
    }
}

void handle_joy1_btn10()
{
    servo[roller] = SERVO_ROLLER_UP;
}

void handle_joy1_btn3()
{
    servo[autoElbow] = SERVO_AUTOELBOW_UP;
}

void handle_joy1_rtu()
{
	servo[leftFang] = LEFT_FANG_STOW;
	servo[rightFang] = RIGHT_FANG_STOW;
}

void handle_joy1_rtd()
{
	servo[leftFang] = LEFT_FANG_DEPLOY;
	servo[rightFang] = RIGHT_FANG_DEPLOY;
}

void handle_joy1_ltu()
{
    if (!deadman_ltu_running) {
        startTask(deadman_ltu);
    }
}

void handle_joy1_ltd()
{
    if (!deadman_ltd_running) {
        startTask(deadman_ltd);
    }
}

void handle_joy2_rtu()
{
    int c;

    for (c = SERVO_ROLLER_UP; c <= SERVO_ROLLER_OSC_DOWN; c++) {
        servo[roller] = c;
        wait1Msec(10);
    }
    servo[roller] = SERVO_ROLLER_UP;
}

void handle_joy1_event(joystick_event_t event)
{
    switch (event) {
    case BUTTON_ONE:
        handle_joy1_btn1();
        break;
    case BUTTON_THREE:
        handle_joy1_btn3();
        break;
    case BUTTON_FOUR:
        handle_joy1_btn4();
        break;
    case BUTTON_TEN:
		handle_joy1_btn10();
		break;
    case RIGHT_TRIGGER_UP:
        handle_joy1_rtu();
        break;
    case RIGHT_TRIGGER_DOWN:
        handle_joy1_rtd();
        break;
    case LEFT_TRIGGER_UP:
        handle_joy1_ltu();
        break;
    case LEFT_TRIGGER_DOWN:
        handle_joy1_ltd();
        break;
    }

    startTask(debounceTask);
}

void handle_joy2_event(joystick_event_t event)
{
    switch(event) {
    case RIGHT_TRIGGER_UP:
        handle_joy2_rtu();
        break;
    }

    startTask(debounceTask);
}

#define RAMP_SPEED 30
#define RAMP_SCORE_DELTA 932
#define RAMP_PICKUP_DELTA 932

void handle_tophat_up()
{
    nMotorEncoder[rampLeft] = 0;

    motor[rampLeft] = RAMP_SPEED;
    motor[rampRight] = RAMP_SPEED;

    while (abs(nMotorEncoder[rampLeft]) < RAMP_SCORE_DELTA) {
    }

    motor[rampLeft] = 0;
    motor[rampRight] = 0;
}

void handle_tophat_down()
{
    nMotorEncoder[rampLeft] = 0;

    motor[rampLeft] = -RAMP_SPEED;
    motor[rampRight] = -RAMP_SPEED;

    while (abs(nMotorEncoder[rampLeft]) < RAMP_PICKUP_DELTA) {
    }

    motor[rampLeft] = 0;
    motor[rampRight] = 0;

}

task main()
{
    short right_y;
    short left_y;

    debounce = false;

    initializeRobot();

    waitForStart();   // wait for start of tele-op phase

    bFloatDuringInactiveMotorPWM = false;
	conveyor_enter_state(CONVEYOR_FORWARD);

	startTask(validate_conveyor);
    startTask(ball_watch);

    servo[roller] = SERVO_ROLLER_UP;
	servo[leftGoalGuide] = LEFT_GUIDE_DEPLOY;
	servo[rightGoalGuide] = RIGHT_GUIDE_DEPLOY;

    // servo[autoElbow] = 37;

    //startTask(ball_watch);

    // StartTask(endGameTimer);

    while (true) {

        motor[motorA] = 0;
        motor[motorB] = 0;

        getJoystickSettings(joystick);

        if (!debounce) {
	        if (joy1Btn(Btn1)) {
	            handle_joy1_event(BUTTON_ONE);
	        } else if (joy1Btn(Btn4)) {
	            handle_joy1_event(BUTTON_FOUR);
	        } else if (joy1Btn(Btn10)) {
        		handle_joy1_event(BUTTON_TEN);
	        } else if (joy1Btn(Btn3)) {
        		handle_joy1_event(BUTTON_THREE);
	        } else if (joy1Btn(Btn5)) {
	            handle_joy1_event(LEFT_TRIGGER_UP);
	        } else if (joy1Btn(Btn7)) {
	            handle_joy1_event(LEFT_TRIGGER_DOWN);
	        } else if (joy1Btn(Btn6)) {
	            handle_joy1_event(RIGHT_TRIGGER_UP);
	        } else if (joy1Btn(Btn8)) {
	            handle_joy1_event(RIGHT_TRIGGER_DOWN);
	        } else if (joy2Btn(Btn6)) {
	            handle_joy2_event(RIGHT_TRIGGER_UP);
            } else if (joystick.joy2_TopHat == 0) { // Up d-pad
                handle_tophat_up();
            } else if (joystick.joy2_TopHat == 4) { // Down d-pad
                handle_tophat_down();
	        }
        }

        //if (drive_multiplier) {
            //right_y = joystick.joy1_y2;
            //left_y = joystick.joy1_y1;
        //} else {
            left_y = joystick.joy2_y1;
            right_y = joystick.joy2_y2;
        //}

        if (abs(right_y) > 10) {
	    	motor[driveFrontRight] = drive_multiplier * right_y * 0.80;
	    	motor[driveRearRight] = drive_multiplier * right_y * 0.80;
		} else {
		    motor[driveFrontRight] = 0;
		    motor[driveRearRight] = 0;
		}

        if (abs(left_y) > 10) {
		    motor[driveFrontLeft] = drive_multiplier * left_y * 0.80;
		    motor[driveRearLeft] = drive_multiplier * left_y * 0.80;
		} else {
		    motor[driveFrontLeft] = 0;
		    motor[driveRearLeft] = 0;
		}
    }
}
