#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define ROTATION         60
#define LEFT_HOPPER_DOWN 106
#define LEFT_HOPPER_UP LEFT_HOPPER_DOWN + ROTATION

#define RIGHT_HOPPER_DOWN 146
#define RIGHT_HOPPER_UP RIGHT_HOPPER_DOWN - ROTATION

#define SERVO_MAX 255
#define SERVO_MIN 0

bool done;

task calibrateServo()
{
    int val;

    while (!done) {
	    val = ServoValue[rightHopper];
        servo[rightHopper] = ++val;
		nxtDisplayCenteredTextLine(4, "Location: %d", val);
        wait1Msec(300);
    }
}

task main()
{
    done = false;

    servoChangeRate[leftHopper]  = 5;
    servoChangeRate[rightHopper] = 5;

    servo[leftHopper] = SERVO_MAX/2;
    servo[rightHopper] = SERVO_MAX/2;

    wait1Msec(1000);

    StartTask(calibrateServo);

    while (1) {
        if (nNxtButtonPressed == 3) {
            done = true;
        }
    }

    while(1) {}
}
