#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     elevTouch,      sensorTouch)
#pragma config(Sensor, S4,     HTMC,           sensorI2CCustom)
#pragma config(Motor,  motorA,          waterWheel,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftElevator,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightElevator, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    right,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    left,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    rightHopper,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    leftHopper,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    shovel,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SERVO_MAX 255

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

bool done;

task calibrateServo()
{
    int val;

    servoChangeRate[shovel]  = 5;
    servo[shovel] = SERVO_MAX/2;
    wait1Msec(500);

    while (!done) {
	    val = ServoValue[shovel];
        servo[shovel] = --val;
		nxtDisplayCenteredTextLine(4, "Location: %d", val);
        wait1Msec(300);
    }
}

task main()
{
    done = false;

    StartTask(calibrateServo);

    while (1) {
        if (nNxtButtonPressed == 3) {
            done = true;
        }
    }

    while(1) {}
}
