#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          waterWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftElevator,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightElevator, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    right,                tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    left,                 tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    rightHopper,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    leftHopper,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    nMotorEncoder[conveyor] = 0;

    motor[conveyor] = 30;
    while (nMotorEncoder[conveyor] < 1500) {}
    motor[conveyor] = 0;

    while (1) {}
}
