#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../library/sensors/drivers/hitechnic-sensormux.h"
#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"
#include "../library/sensors/drivers/hitechnic-compass.h"
#include "../library/sensors/drivers/hitechnic-protoboard.h"
#include "../library/auto_defs.h"
#include "../library/DrivetrainSquare.c"
#include "../library/dead_reckon.h"
#include "../library/mux_defs.h"

task main()
{
    init_path();

    add_segment(-400, 0, 100);
    add_segment(0, 0, 0);

    dead_reckon();

    while (1) {}
}
