#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ENCPERINCH 108

#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"
#include "..\library\sensors\drivers\hitechnic-compass.h"
#include "..\library\DrivetrainSquare.c"
#include "..\library\nxt_buttons.h"

int travelDistance[] = {14, 8, 19, 11};

task main()
{
    int j;
    bool done;

    for (int i = 0; i < 4; i++) {
        moveBackward(travelDistance[i], 100);
        j = travelDistance[i];
        done = false;
        while (!done) {
            nxtDisplayTextLine(4, "Distance %d", j);
            if (isRightArrowButtonPressed()) {
                moveBackward(1, 50);
                j++;
            } else if (isLeftArrowButtonPressed()) {
                moveForward(1, 50);
                j--;
            } else if (isMainButtonPressed()) {
                done = true;
            }
        }
    }

    while (true) {}
}
