#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftElevator,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightElevator, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    right,                tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    left,                 tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SLOP_FACTOR 80

void speed(int val)
{
    motor[leftElevator] = val;
    motor[rightElevator] = val;
}

task syncController()
{
    int leftVal;
    int rightVal;
    int delta, max = 0;
    bool done = false;

    nMotorEncoder[leftElevator] = 0;
    nMotorEncoder[rightElevator] = 0;

    while (!done) {
	    leftVal = nMotorEncoder[leftElevator];
	    rightVal = nMotorEncoder[rightElevator];

        nxtDisplayCenteredTextLine(1, "left: %d", leftVal);
        nxtDisplayCenteredTextLine(2, "right: %d", rightVal);

        delta = abs(leftVal - rightVal);
        nxtDisplayCenteredTextLine(3, "delta: %d", delta);

        if (delta > max) {
            max = delta;
            nxtDisplayCenteredTextLine(5, "max: %d", max);
        }

	    if (abs(leftVal - rightVal) > SLOP_FACTOR) {
            if (left < right) {
                nxtDisplayCenteredTextLine(4, "stop right");
                speed(0);
            } else if (right < left) {
                nxtDisplayCenteredTextLine(4, "stop left");
                speed(0);
            }
	    } else {
            nxtDisplayCenteredTextLine(4, "go all");
            speed(20);
        }
    }
}

task main()
{
    speed(10);

    StartTask(syncController);

    wait1Msec(3000);

    speed(0);

    while(1) {}
}
