#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../library/nxt_buttons.h"

#define ELEV_ENCODER_UP_VAL -24000

task elevatorSoftwareStop()
{
    long val;

    val = nMotorEncoder[rightElevator];
    while (val > ELEV_ENCODER_UP_VAL) {
        val = nMotorEncoder[rightElevator];
    }
    motor[leftElevator] = 0;
    motor[rightElevator] = 0;
}

task main()
{
    nMotorEncoder[leftElevator] = 0;
    nMotorEncoder[rightElevator] = 0;

    motor[leftElevator] = 20;
    motor[rightElevator] = -20;

    StartTask(elevatorSoftwareStop);

    while (1) {
        if (isMainButtonPressed()) {
            motor[leftElevator] = 0;
            motor[rightElevator] = 0;
        }
        nxtDisplayTextLine(2, "Left %d", nMotorEncoder[leftElevator]);
        nxtDisplayTextLine(3, "Right %d", nMotorEncoder[rightElevator]);
    }
}
