#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftElevator,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightElevator, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DISTANCE 200

task main()
{
    bool doneRight = false;
    bool doneLeft = false;

	nMotorEncoder[leftElevator] = 0;
	nMotorEncoder[rightElevator] = 0;
	nMotorEncoderTarget[leftElevator] = DISTANCE;
	nMotorEncoderTarget[rightElevator] = DISTANCE;
	motor[leftElevator] = 20;
	motor[rightElevator] = -20;

	while (!doneRight && !doneLeft) {
        if (nMotorRunState[leftElevator] == runStateIdle) {
            motor[leftElevator] = 0;
            doneLeft = true;
        }
        if (nMotorRunState[rightElevator] == runStateIdle) {
            motor[rightElevator] = 0;
            doneRight = true;
        }
    }
}
