#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../library/nxt_buttons.h"

task main()
{
    nMotorEncoder[leftElevator] = 0;
    nMotorEncoder[rightElevator] = 0;

    wait1Msec(1000);

    motor[leftElevator] = 20;
    motor[rightElevator] = -20;

    // StartTask(syncController);

    while (1) {
        if (isMainButtonPressed()) {
            motor[leftElevator] = 0;
            motor[rightElevator] = 0;
        }
        nxtDisplayTextLine(2, "Left %d", nMotorEncoder[leftElevator]);
        nxtDisplayTextLine(3, "Right %d", nMotorEncoder[rightElevator]);
    }
}
