#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftElevator,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightElevator, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task syncController()
{
    int leftVal;
    int rightVal;
    bool done = false;

    while (!done) {
	    leftVal = nMotorEncoder[leftElevator];
	    rightVal = nMotorEncoder[rightElevator];

        nxtDisplayCenteredTextLine(1, "left: %d\n", leftVal);
        nxtDisplayCenteredTextLine(2, "right: %d\n", rightVal);
    }
}

task main()
{
    motor[leftElevator] = 20;
    motor[rightElevator] = 20;

    StartTask(syncController);

    wait1Msec(1000);

    motor[leftElevator] = 0;
    motor[rightElevator] = 0;


    while(1) {}
}
