#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[driveFrontRight] = 0;
	nMotorEncoder[driveFrontLeft] = 0;
	nMotorEncoder[driveRearRight] = 0;
	nMotorEncoder[driveRearLeft] = 0;

	nMotorEncoderTarget[driveFrontRight] = 8000;
	nMotorEncoderTarget[driveFrontLeft] = 8000;
	nMotorEncoderTarget[driveRearRight] = 8000;
	nMotorEncoderTarget[driveRearLeft] = 8000;

    motor[driveFrontRight] = 100;
    motor[driveFrontLeft] = 100;
    motor[driveRearRight] = 100;
    motor[driveRearLeft] = 100;

    while ((nMotorRunState[driveFrontRight] != runStateIdle) &&
           (nMotorRunState[driveFrontLeft] != runStateIdle) &&
           (nMotorRunState[driveRearRight] != runStateIdle) &&
           (nMotorRunState[driveRearLeft] != runStateIdle)) {
	    nxtDisplayTextLine(2, "F Right: %d", nMotorEncoder[driveFrontRight]);
	    nxtDisplayTextLine(3, "F Left: %d", nMotorEncoder[driveFrontLeft]);
	    nxtDisplayTextLine(4, "R Right: %d", nMotorEncoder[driveRearRight]);
	    nxtDisplayTextLine(5, "R Left: %d", nMotorEncoder[driveRearLeft]);
    }

    PlayImmediateTone(60, 1000);

    while (1) {}
}
