#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          waterWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftElevator,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightElevator, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    right,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    left,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    rightHopper,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    leftHopper,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define ROTATION         60
#define LEFT_HOPPER_DOWN 106
#define LEFT_HOPPER_UP LEFT_HOPPER_DOWN + ROTATION

#define RIGHT_HOPPER_DOWN 146
#define RIGHT_HOPPER_UP RIGHT_HOPPER_DOWN - ROTATION

task main()
{
    servoChangeRate[leftHopper]  = 1;
    servoChangeRate[rightHopper] = 1;

    for (int i = 0; i < 5; i++) {

	    servo[leftHopper] = LEFT_HOPPER_UP;
	    servo[rightHopper] = RIGHT_HOPPER_UP;

        wait1Msec(1000);

	    servo[leftHopper] = LEFT_HOPPER_DOWN;
	    servo[rightHopper] = RIGHT_HOPPER_DOWN;

	    wait1Msec(1000);
    }

    while (1) {}
}
