#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../library/sensors/drivers/hitechnic-protoboard.h"
#include "../library/limitSwitch.h"
#include "../library/light_strip.h"

task main()
{
    int val;

    limitSwitchInit(5);
    lightStripInit(0x1F);


    val = HTPBgetIOCfg(HTPB);

    nxtDisplayTextLine(2, "iocfg %x", val);

    while (1) {}

}
