#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S1,     HTIRS2,              sensorI2CCustom)

#include "../library/sensors/drivers/hitechnic-sensormux.h"
#include "../library/sensors/drivers/hitechnic-irseeker-v2.h"
//#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
//#include "../library/rnrr_start.h"

const tMUXSensor IRSeeker = msensor_S2_4;

string sTextLines[8];

void displayText(int nLineNumber, const string cChar, int nValueAC)
{
  string sTemp;

  StringFormat(sTemp,"%4d", nValueAC);
  // Check if the new line is the same as the previous one
  // Only update screen if it's different.
  if (sTemp != sTextLines[nLineNumber])
  {
    string sTemp2;

    sTextLines[nLineNumber] = sTemp;
    StringFormat(sTemp2, "%s:  %s", cChar, sTemp);
    nxtDisplayTextLine(nLineNumber, sTemp2);
  }
}


task main()
{
    bool rtn;
	int acS1, acS2, acS3, acS4, acS5, _dirAC = 0;

    // RNRR_waitForStart();

    tHTIRS2DSPMode _mode = DSP_1200;

    //HTIRS2setDSPMode(HTIRS2, _mode);

    while (1) {

        _dirAC = HTIRS2readACDir(IRSeeker);
        if (_dirAC < 0) {
            nxtDisplayBigTextLine(4, "Error");
            break;
        }

	    if (!HTIRS2readAllACStrength(IRSeeker, acS1, acS2, acS3, acS4, acS5 ))
	        break; // I2C read error occurred

		displayText(1, "D",  _dirAC);
		displayText(2, "0", acS1);
		displayText(3, "1", acS2);
		displayText(4, "2", acS3);
		displayText(5, "3", acS4);
		displayText(6, "4", acS5);
        wait1Msec(300);
    }

    while (1) {}
}
