#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../library/limitSwitch.h"

#define SWITCH_PIN 5

task main()
{
    limitSwitchInit(SWITCH_PIN);

    while (1) {
        /*
         * Using a pullup as input, so when the switch
         * closes the pin sees ground.  So 1 is open 0 is closed
         */
        if (isLimitSwitchClosed()) {
            nxtDisplayTextLine(4, "Closed");
        } else {
            nxtDisplayTextLine(4, "Open");
        }

        wait1Msec(200);
    }
}
