#pragma config(Sensor, S1,     controller_chain, sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\library\ht_motor.h"


task main()
{
    HT_MotorInit(controller_chain);
    HT_MotorSetPIDControl(0, 0, true);
    HT_MotorSetSpeed(0, 0, 10);
    HT_MotorOn(0, 0);
    wait1Msec(2000);
    HT_MotorOff(0, 0);
    wait1Msec(2000);
    HT_MotorOn(0, 0);
    wait1Msec(2000);
    HT_MotorOff(0, 0);

    while (true) {}
}
