#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)*/
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    motor[driveLeft] = 10;

    while (true) {
        nxtDisplayString(2, "Encoder %d", nMotorEncoder[driveLeft]);
        //nxtDisplayString(3, "PWM: %d", motorPWMLevel[driveLeft]);
    }
}
