#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RIGHT_HOPPER_DOWN 143
#define LEFT_HOPPER_DOWN  108
#define ROTATION          100
#define LEFT_HOPPER_UP LEFT_HOPPER_DOWN + ROTATION
#define RIGHT_HOPPER_UP RIGHT_HOPPER_DOWN - ROTATION
#define ELEV_ENCODER_UP_VAL -18000

void raiseHopper()
{
    servo[leftHopper] = LEFT_HOPPER_UP;
    servo[rightHopper] = RIGHT_HOPPER_UP;
}

void lowerHopper()
{
    servo[leftHopper] = LEFT_HOPPER_DOWN;
    servo[rightHopper] = RIGHT_HOPPER_DOWN;
}

task main()
{
    lowerHopper();
    wait1Msec(2000);
    raiseHopper();
    while (true) {}
}
