#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ENCPERINCH 108

#include "..\library\sensors\drivers\hitechnic-compass.h"
#include "..\library\DrivetrainSquare.c"

task main()
{
	turn(90);

    while (true) {}
}
