#pragma config(StandardModel, "tommy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ENCPERINCH 108

#include "..\library\DrivetrainSquare.c"

task main()
{
	rotateClockwise(100, 90);
}
