#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define SERVO_MAX 255
#define SERVO_MIN 0

bool done;

task calibrateServo()
{
    int val;

    while (!done) {
	    val = ServoValue[blockDump];
        servo[blockDump] = ++val;
		nxtDisplayCenteredTextLine(4, "Location: %d", val);
        wait1Msec(300);
    }
}

task main()
{
    done = false;

    servo[blockDump] = SERVO_MAX/2;

    wait1Msec(1000);

    StartTask(calibrateServo);

    while (1) {
        if (nNxtButtonPressed == 3) {
            done = true;
        }
    }

    while(1) {}
}
