#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	servo[leftHopper] = LEFT_HOPPER_UP;
	servo[rightHopper] = RIGHT_HOPPER_UP;
}
