#pragma config(StandardModel, "teddy")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    motor[leftElevator] = 20;
    motor[rightElevator] = -20;

    // StartTask(syncController);

    while(1) {}
}
