#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     elevTouch,      sensorTouch)
#pragma config(Motor,  motorA,          waterWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftElevator,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     driveRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightElevator, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     driveLeft,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    rightHopper,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    leftHopper,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    left,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_6,    right,                tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    long rVal, lVal;

    nMotorEncoder[rightElevator] = 0;
    nMotorEncoder[leftElevator] = 0;

    motor[rightElevator] = 20;
    motor[leftElevator] = 20;

    while (1) {
	    rVal = nMotorEncoder[rightElevator];
	    lVal = nMotorEncoder[leftElevator];

        nxtDisplayCenteredTextLine(3, "rVal: %d", rVal);
        nxtDisplayCenteredTextLine(4, "lVal: %d", lVal);
    }
}
